"""Aruba Central platform module."""

import importlib

from fastmcp import FastMCP
from loguru import logger

from hpe_networking_mcp.config import ServerConfig

# Tool categories mapped to module names and their tool names
TOOLS = {
    "sites": [
        "central_add_devices_to_device_group",
        "central_add_devices_to_site",
        "central_bulk_delete_device_groups",
        "central_bulk_delete_site_collections",
        "central_bulk_delete_sites",
        "central_create_device_group_with_devices",
        "central_get_global_scope",
        "central_get_hierarchy",
        "central_get_site_health",
        "central_get_site_name_id_mapping",
        "central_get_sites",
        "central_remove_devices_from_device_group",
    ],
    "devices": [
        "central_find_device",
        "central_get_devices",
    ],
    "clients": [
        "central_find_client",
        "central_get_clients",
    ],
    "alerts": [
        "central_clear_alerts",
        "central_defer_alerts",
        "central_get_alert_action_status",
        "central_get_alert_classification",
        "central_get_alerts",
        "central_reactivate_alerts",
        "central_set_alert_priority",
    ],
    "alert_configs": [
        "central_create_alert_config",
        "central_get_alert_configs",
        "central_reset_alert_config",
        "central_update_alert_config",
    ],
    "events": [
        "central_get_events",
        "central_get_events_count",
    ],
    "monitoring": [
        "central_get_ap_details",
        "central_get_ap_wlans",
        "central_get_aps",
        "central_get_gateway_details",
        "central_get_switch_details",
    ],
    "wlans": [
        "central_get_wlan_stats",
        "central_get_wlans",
    ],
    "audit_logs": [
        "central_get_audit_log_detail",
        "central_get_audit_logs",
    ],
    "stats": [
        "central_get_ap_stats",
        "central_get_ap_utilization",
        "central_get_gateway_stats",
        "central_get_gateway_utilization",
        "central_get_gateway_wan_availability",
        "central_get_tunnel_health",
    ],
    "switch_poe": [
        "central_get_switch_hardware_trends",
        "central_get_switch_poe",
    ],
    "applications": ["central_get_applications"],
    "troubleshooting": [
        "central_cable_test",
        "central_ping",
        "central_show_commands",
        "central_traceroute",
    ],
    "actions": [
        "central_disconnect_client_gateway",
        "central_disconnect_client_switch",
        "central_disconnect_clients_gateway",
        "central_disconnect_users_ap",
        "central_disconnect_users_ssid",
        "central_poe_bounce_gateway",
        "central_poe_bounce_switch",
        "central_port_bounce_gateway",
        "central_port_bounce_switch",
    ],
    "scope": [
        "central_get_committed_config",
        "central_get_devices_in_scope",
        "central_get_effective_config",
        "central_get_scope_diagram",
        "central_get_scope_resources",
        "central_get_scope_tree",
    ],
    "wlan_profiles": [
        "central_get_wlan_profiles",
        "central_manage_wlan_profile",
    ],
    "roles": ["central_get_role_with_policy"],
    "config_assignments": [
        "central_get_config_assignments",
        "central_manage_config_assignment",
    ],
    "configuration": [
        "central_manage_device_group",
        "central_manage_site",
        "central_manage_site_collection",
    ],
    "config_health": [
        "central_get_device_config_issues",
        "central_get_devices_config_health",
        "central_resync_device_config",
    ],
    "firmware": ["central_recommend_firmware"],
    "wids": ["central_get_wids_monitored_aps"],
    "application_experience": [
        "central_get_app_bandwidth_contracts",
        "central_get_arc",
        "central_manage_app_bandwidth_contracts",
        "central_manage_arc",
    ],
    "central_nac": [
        "central_get_airpass_approval",
        "central_get_auth_profiles",
        "central_get_authz_policies",
        "central_get_custom_messages",
        "central_get_default_custom_messages",
        "central_get_identity_stores",
        "central_get_message_providers",
        "central_get_overrides",
        "central_get_portals",
        "central_get_skins",
        "central_get_static_tag",
        "central_manage_auth_profiles",
        "central_manage_authz_policies",
        "central_manage_custom_messages",
        "central_manage_default_custom_messages",
        "central_manage_identity_stores",
        "central_manage_message_providers",
        "central_manage_overrides",
        "central_manage_portals",
        "central_manage_skins",
        "central_manage_static_tag",
    ],
    "central_nac_service": [
        "central_cnac_certificate_revoke",
        "central_cnac_image_upload",
        "central_cnac_mac_reg_import",
        "central_cnac_named_mpsk_reg_import",
        "central_get_cnac_certificate",
        "central_get_cnac_dpp_reg",
        "central_get_cnac_image",
        "central_get_cnac_image_download",
        "central_get_cnac_job",
        "central_get_cnac_job_error",
        "central_get_cnac_job_input",
        "central_get_cnac_job_status",
        "central_get_cnac_mac_reg",
        "central_get_cnac_mac_reg_export",
        "central_get_cnac_named_mpsk_reg",
        "central_get_cnac_named_mpsk_reg_export",
        "central_get_cnac_visitor",
        "central_get_cnac_visitor_export",
        "central_manage_cnac_dpp_reg",
        "central_manage_cnac_job",
        "central_manage_cnac_mac_reg",
        "central_manage_cnac_named_mpsk_reg",
        "central_manage_cnac_static_tags_usage",
        "central_manage_cnac_visitor",
    ],
    "config_management": [
        "central_get_config_checkpoint",
        "central_get_device_persona_mapping",
        "central_manage_config_checkpoint",
        "central_manage_persona_assignment",
    ],
    "extensions": [
        "central_get_psm",
        "central_get_splunk_instances",
        "central_get_vsphere_instances",
        "central_manage_psm",
        "central_manage_splunk_instances",
        "central_manage_vsphere_instances",
    ],
    "firmware_policy": [
        "central_get_firmware_compliance",
        "central_manage_firmware_compliance",
    ],
    "gateway_clustering_orchestration": [
        "central_get_gw_cluster_intent_config",
        "central_manage_gw_cluster_intent_config",
    ],
    "high_availability": [
        "central_get_gateway_clusters",
        "central_get_stacks",
        "central_get_vsf_templates",
        "central_get_vsx_profiles",
        "central_manage_gateway_clusters",
        "central_manage_stacks",
        "central_manage_vsf_templates",
        "central_manage_vsx_profiles",
    ],
    "interfaces": [
        "central_get_ap_port_profiles",
        "central_get_ap_uplinks",
        "central_get_cdp",
        "central_get_device_profile",
        "central_get_dhcp_client",
        "central_get_ethernet_interfaces",
        "central_get_fault_monitor",
        "central_get_gw_port_profiles",
        "central_get_interface_profiles",
        "central_get_lacp",
        "central_get_lldp",
        "central_get_loopback_interfaces",
        "central_get_mgmt_interfaces",
        "central_get_mirror_endpoint",
        "central_get_mirrors",
        "central_get_portchannels",
        "central_get_sflow",
        "central_get_static_macs",
        "central_get_sub_interfaces",
        "central_get_sw_port_profiles",
        "central_get_ufd",
        "central_get_vlan_interfaces",
        "central_manage_ap_port_profiles",
        "central_manage_ap_uplinks",
        "central_manage_cdp",
        "central_manage_device_profile",
        "central_manage_dhcp_client",
        "central_manage_ethernet_interfaces",
        "central_manage_fault_monitor",
        "central_manage_gw_port_profiles",
        "central_manage_interface_profiles",
        "central_manage_lacp",
        "central_manage_lldp",
        "central_manage_loopback_interfaces",
        "central_manage_mgmt_interfaces",
        "central_manage_mirror_endpoint",
        "central_manage_mirrors",
        "central_manage_portchannels",
        "central_manage_sflow",
        "central_manage_static_macs",
        "central_manage_sub_interfaces",
        "central_manage_sw_port_profiles",
        "central_manage_ufd",
        "central_manage_vlan_interfaces",
    ],
    "iot": [
        "central_get_usb",
        "central_manage_usb",
    ],
    "miscellaneous": [
        "central_get_device_firmware",
        "central_get_dsm",
        "central_get_features",
        "central_get_node_operations",
        "central_get_overlay_wlan",
        "central_get_vsx_config",
        "central_get_vxlan",
        "central_manage_device_firmware",
        "central_manage_dsm",
        "central_manage_features",
        "central_manage_node_operations",
        "central_manage_overlay_wlan",
        "central_manage_vsx_config",
        "central_manage_vxlan",
    ],
    "named_object": [
        "central_get_aliases",
        "central_get_named_conditions",
        "central_get_net_services",
        "central_manage_aliases",
        "central_manage_named_conditions",
        "central_manage_net_services",
    ],
    "network_services": [
        "central_get_dhcp_pool",
        "central_get_dhcp_relay",
        "central_get_dhcp_server",
        "central_get_dhcp_snooping",
        "central_get_dhcp_snooping_interface",
        "central_get_dynamic_arp_inspection_interface",
        "central_get_external_storage",
        "central_get_ip_source_lockdown",
        "central_get_ip_source_lockdown_interface",
        "central_get_ipsla",
        "central_get_mgmd_global",
        "central_get_multicast_dns",
        "central_get_nae_lite",
        "central_get_nd_snooping",
        "central_get_nd_snooping_interface",
        "central_get_ptp",
        "central_get_qos_global",
        "central_get_qos_queues",
        "central_get_qos_schedules",
        "central_get_qos_thresholds",
        "central_get_source_ip_bindings",
        "central_get_udp_broadcast_forwarders",
        "central_manage_dhcp_pool",
        "central_manage_dhcp_relay",
        "central_manage_dhcp_server",
        "central_manage_dhcp_snooping",
        "central_manage_dhcp_snooping_interface",
        "central_manage_dynamic_arp_inspection_interface",
        "central_manage_external_storage",
        "central_manage_ip_source_lockdown",
        "central_manage_ip_source_lockdown_interface",
        "central_manage_ipsla",
        "central_manage_mgmd_global",
        "central_manage_multicast_dns",
        "central_manage_nae_lite",
        "central_manage_nd_snooping",
        "central_manage_nd_snooping_interface",
        "central_manage_ptp",
        "central_manage_qos_global",
        "central_manage_qos_queues",
        "central_manage_qos_schedules",
        "central_manage_qos_thresholds",
        "central_manage_source_ip_bindings",
        "central_manage_udp_broadcast_forwarders",
    ],
    "roles_policy": [
        "central_get_object_groups",
        "central_get_policies",
        "central_get_policy_group_list",
        "central_get_policy_groups",
        "central_get_role_acls",
        "central_get_role_gpids",
        "central_get_roles",
        "central_manage_object_groups",
        "central_manage_policies",
        "central_manage_policy_group_list",
        "central_manage_policy_groups",
        "central_manage_role_acls",
        "central_manage_role_gpids",
        "central_manage_roles",
    ],
    "routing_overlays": [
        "central_get_advanced_intelligent_forwarding",
        "central_get_aspath_lists",
        "central_get_bfd",
        "central_get_bgp",
        "central_get_community_lists",
        "central_get_evpn",
        "central_get_ip_routing",
        "central_get_l3_route",
        "central_get_mpls",
        "central_get_msdp",
        "central_get_multicast_global",
        "central_get_multicast_static_route",
        "central_get_nexthop_groups",
        "central_get_ospfv2",
        "central_get_ospfv3",
        "central_get_pim_router",
        "central_get_prefix_lists",
        "central_get_rip",
        "central_get_route_maps",
        "central_get_static_route",
        "central_get_tracking_object",
        "central_get_vrfs",
        "central_manage_advanced_intelligent_forwarding",
        "central_manage_aspath_lists",
        "central_manage_bfd",
        "central_manage_bgp",
        "central_manage_community_lists",
        "central_manage_evpn",
        "central_manage_ip_routing",
        "central_manage_l3_route",
        "central_manage_mpls",
        "central_manage_msdp",
        "central_manage_multicast_global",
        "central_manage_multicast_static_route",
        "central_manage_nexthop_groups",
        "central_manage_ospfv2",
        "central_manage_ospfv3",
        "central_manage_pim_router",
        "central_manage_prefix_lists",
        "central_manage_rip",
        "central_manage_route_maps",
        "central_manage_static_route",
        "central_manage_tracking_object",
        "central_manage_vrfs",
    ],
    "scope_management": [
        "central_device_collections_bulk_delete",
        "central_get_device_collections",
        "central_manage_device_collection_add_devices",
        "central_manage_device_collection_create_and_add_devices",
        "central_manage_device_collection_remove_devices",
        "central_manage_device_collections",
    ],
    "security": [
        "central_get_aaa_profile",
        "central_get_auth_server_global_config",
        "central_get_auth_servers",
        "central_get_auth_survivability",
        "central_get_bcn_rpt_req_profiles",
        "central_get_captive_portal",
        "central_get_certificate_rcp",
        "central_get_certificate_store",
        "central_get_certificate_usage",
        "central_get_certificates",
        "central_get_copp",
        "central_get_device_certificates",
        "central_get_dot11k_profiles",
        "central_get_dot1xauth",
        "central_get_dot1xsupp",
        "central_get_est_profiles",
        "central_get_firewall",
        "central_get_gw_certificate_usage",
        "central_get_internal_user",
        "central_get_keychains",
        "central_get_mac_lockout",
        "central_get_macauth",
        "central_get_macsec",
        "central_get_mka",
        "central_get_net_groups",
        "central_get_passpoint_identity",
        "central_get_port_security",
        "central_get_radius_modifiers",
        "central_get_rrm_ie_profiles",
        "central_get_server_groups",
        "central_get_stateful_dot1x_profiles",
        "central_get_ubt",
        "central_manage_aaa_profile",
        "central_manage_auth_server_global_config",
        "central_manage_auth_servers",
        "central_manage_auth_survivability",
        "central_manage_bcn_rpt_req_profiles",
        "central_manage_captive_portal",
        "central_manage_certificate_rcp",
        "central_manage_certificate_store",
        "central_manage_certificate_usage",
        "central_manage_certificates",
        "central_manage_copp",
        "central_manage_device_certificates",
        "central_manage_dot11k_profiles",
        "central_manage_dot1xauth",
        "central_manage_dot1xsupp",
        "central_manage_est_profiles",
        "central_manage_firewall",
        "central_manage_gw_certificate_usage",
        "central_manage_internal_user",
        "central_manage_keychains",
        "central_manage_mac_lockout",
        "central_manage_macauth",
        "central_manage_macsec",
        "central_manage_mka",
        "central_manage_net_groups",
        "central_manage_passpoint_identity",
        "central_manage_port_security",
        "central_manage_radius_modifiers",
        "central_manage_rrm_ie_profiles",
        "central_manage_server_groups",
        "central_manage_stateful_dot1x_profiles",
        "central_manage_ubt",
    ],
    "services": [
        "central_get_airgroup_policies",
        "central_get_airgroup_servers",
        "central_get_airgroup_service_definitions",
        "central_get_airgroup_system",
        "central_get_location",
        "central_manage_airgroup_policies",
        "central_manage_airgroup_servers",
        "central_manage_airgroup_service_definitions",
        "central_manage_airgroup_system",
        "central_manage_location",
    ],
    "system": [
        "central_get_ap_system",
        "central_get_container_networks",
        "central_get_containers",
        "central_get_countermon",
        "central_get_custom_get_api",
        "central_get_db_observer",
        "central_get_ddns",
        "central_get_dns",
        "central_get_dump_server",
        "central_get_gw_system",
        "central_get_hardware_modules",
        "central_get_http_proxy_servers",
        "central_get_ip_source_interfaces",
        "central_get_ipm",
        "central_get_job_scheduler",
        "central_get_local_management",
        "central_get_logging",
        "central_get_management_server",
        "central_get_management_user_groups",
        "central_get_management_users",
        "central_get_nae_agents",
        "central_get_nae_scripts",
        "central_get_ntp",
        "central_get_packet_capture",
        "central_get_remote_management",
        "central_get_rmon_alarms",
        "central_get_snmp",
        "central_get_snmp_trap",
        "central_get_speed_test",
        "central_get_switch_chassis",
        "central_get_switch_profiles",
        "central_get_switch_system",
        "central_get_sysmon",
        "central_get_system_info",
        "central_get_telemetry",
        "central_get_time_ranges",
        "central_manage_ap_system",
        "central_manage_container_networks",
        "central_manage_containers",
        "central_manage_countermon",
        "central_manage_db_observer",
        "central_manage_ddns",
        "central_manage_dns",
        "central_manage_dump_server",
        "central_manage_gw_system",
        "central_manage_hardware_modules",
        "central_manage_http_proxy_servers",
        "central_manage_ip_source_interfaces",
        "central_manage_ipm",
        "central_manage_job_scheduler",
        "central_manage_local_management",
        "central_manage_logging",
        "central_manage_management_server",
        "central_manage_management_user_groups",
        "central_manage_management_users",
        "central_manage_nae_agents",
        "central_manage_nae_scripts",
        "central_manage_ntp",
        "central_manage_packet_capture",
        "central_manage_remote_management",
        "central_manage_rmon_alarms",
        "central_manage_snmp",
        "central_manage_snmp_trap",
        "central_manage_speed_test",
        "central_manage_switch_chassis",
        "central_manage_switch_profiles",
        "central_manage_switch_system",
        "central_manage_sysmon",
        "central_manage_system_info",
        "central_manage_telemetry",
        "central_manage_time_ranges",
    ],
    "telemetry": [
        "central_get_client_insight",
        "central_get_client_iptracker",
        "central_get_client_iptracker_interface",
        "central_get_devicefingerprinting",
        "central_get_devicefingerprinting_interface",
        "central_get_devicefingerprinting_profile",
        "central_get_flow_tracking",
        "central_get_ipfix_flow_exporter",
        "central_get_traffic_insight",
        "central_manage_client_insight",
        "central_manage_client_iptracker",
        "central_manage_client_iptracker_interface",
        "central_manage_devicefingerprinting",
        "central_manage_devicefingerprinting_interface",
        "central_manage_devicefingerprinting_profile",
        "central_manage_flow_tracking",
        "central_manage_ipfix_flow_exporter",
        "central_manage_traffic_insight",
    ],
    "tunnels": [
        "central_get_tunnel",
        "central_get_tunnel_groups",
        "central_manage_tunnel",
        "central_manage_tunnel_groups",
    ],
    "vlans_networks": [
        "central_get_erps",
        "central_get_layer2_vlan",
        "central_get_loop_protect",
        "central_get_mvrp",
        "central_get_named_vlan",
        "central_get_smartlink",
        "central_get_static_neighbor",
        "central_get_stp",
        "central_get_stp_gw",
        "central_get_vrrp",
        "central_get_vrrp_global",
        "central_manage_erps",
        "central_manage_layer2_vlan",
        "central_manage_layer2_vlan_range",
        "central_manage_loop_protect",
        "central_manage_mvrp",
        "central_manage_named_vlan",
        "central_manage_smartlink",
        "central_manage_static_neighbor",
        "central_manage_stp",
        "central_manage_stp_gw",
        "central_manage_vrrp",
        "central_manage_vrrp_global",
    ],
    "wireless": [
        "central_get_alg",
        "central_get_ids",
        "central_get_mesh",
        "central_get_mpsk_local",
        "central_get_passpoint",
        "central_get_radio",
        "central_manage_alg",
        "central_manage_ids",
        "central_manage_mesh",
        "central_manage_mpsk_local",
        "central_manage_passpoint",
        "central_manage_radio",
    ],
    "mrt_msp": ["central_list_msp_tenants"],
    "mrt_insights": ["central_get_insights"],
    "mrt_reporting": [
        "central_get_report_runs",
        "central_get_reports",
        "central_update_report",
    ],
    "mrt_webhooks": [
        "central_get_webhook",
        "central_get_webhooks",
        "central_manage_webhook",
        "central_rotate_webhook_hmac_key",
    ],
    "mrt_services": [
        "central_delete_ap_ranging_scan",
        "central_get_ap_ranging_scan",
        "central_get_ap_ranging_scans",
        "central_get_asset_tag",
        "central_get_asset_tags",
        "central_get_device_location",
        "central_get_fco_resp_info",
        "central_get_fco_resp_info_all",
        "central_get_location_analytics_site_insights",
        "central_get_location_analytics_trends",
        "central_get_site_device_location",
        "central_get_site_device_locations",
        "central_get_wifi_clients_locations",
        "central_manage_asset_tag_metadata",
        "central_manage_device_location",
        "central_start_ap_ranging_scan",
    ],
    "mrt_sitemaps": [
        "central_get_buildings",
        "central_get_catalogue_aps",
        "central_get_floor",
        "central_get_floor_image",
        "central_get_floor_walls",
        "central_get_floor_zones",
        "central_get_sitemap_devices",
        "central_get_sitemap_import_status",
        "central_get_sitemap_summary",
        "central_get_wall_types",
        "central_import_sitemap",
        "central_manage_building",
        "central_manage_floor",
        "central_manage_floor_walls",
        "central_manage_floor_zones",
        "central_manage_sitemap_devices",
        "central_manage_wall_types",
        "central_set_floor_image",
        "central_set_floor_scale",
    ],
    "mrt_health": [
        "central_get_site_health_detail",
        "central_get_sites_client_health",
        "central_get_tenant_client_health",
        "central_get_tenant_device_health",
    ],
    "mrt_clients": [
        "central_get_client_detail",
        "central_get_client_mobility_trail",
        "central_get_client_onboarding_score",
        "central_get_client_onboarding_stage_count",
        "central_get_client_onboarding_stage_export",
        "central_get_client_onboarding_stage_reasons",
        "central_get_clients_topn_usage",
        "central_get_clients_trend",
        "central_get_firewall_sessions",
    ],
    "mrt_topology": [
        "central_delete_device",
        "central_get_device_inventory",
        "central_get_isolated_devices",
        "central_get_neighbours",
        "central_get_topology",
        "central_get_unmanaged_device",
        "central_update_device",
    ],
    "mrt_switch": [
        "central_get_switch_hardware_categories",
        "central_get_switch_interface_trends",
        "central_get_switch_lag",
        "central_get_switch_stack_members",
        "central_get_switch_vlans",
        "central_get_switch_vsx",
        "central_get_switches",
        "central_get_switches_topn_interface_trends",
    ],
    "mrt_ap": [
        "central_get_ap_port_trend",
        "central_get_ap_ports",
        "central_get_ap_radio_trend",
        "central_get_ap_radios",
        "central_get_ap_trend",
        "central_get_ap_tunnel",
        "central_get_ap_tunnel_trend",
        "central_get_ap_tunnels",
        "central_get_ap_wlan_throughput",
        "central_get_ap_wlans_monitoring",
        "central_get_applications_v1",
        "central_get_bssids",
        "central_get_radios",
        "central_get_swarm",
        "central_get_swarms",
        "central_get_top_aps_by_usage",
        "central_get_wlan_monitoring_detail",
        "central_get_wlans_monitoring",
    ],
    "mrt_gateway": [
        "central_get_cluster_capacity_trends",
        "central_get_cluster_members",
        "central_get_cluster_summary",
        "central_get_gateway_dhcp",
        "central_get_gateway_port",
        "central_get_gateway_port_trend",
        "central_get_gateway_ports",
        "central_get_gateway_trend",
        "central_get_gateway_tunnel",
        "central_get_gateway_tunnel_trend",
        "central_get_gateway_tunnels",
        "central_get_gateway_tunnels_health_summary",
        "central_get_gateway_uplink",
        "central_get_gateway_uplink_probe_performance",
        "central_get_gateway_uplink_probes",
        "central_get_gateway_uplink_trend",
        "central_get_gateway_uplink_vpn_availability",
        "central_get_gateway_uplinks",
        "central_get_gateway_vlan_runtime",
        "central_get_gateway_vlans_runtime",
        "central_get_gateways",
    ],
    "mrt_troubleshooting": [
        "central_disconnect_client_all_on_gateway",
        "central_disconnect_client_by_mac_on_gateway",
        "central_disconnect_user_all_on_ap",
        "central_disconnect_user_by_mac_on_ap",
        "central_disconnect_user_by_network",
        "central_get_arp_table",
        "central_get_event_extra_attributes",
        "central_get_troubleshooting_task_status",
        "central_halt_gateway",
        "central_iperf_test",
        "central_list_supported_show_commands",
        "central_list_troubleshooting_tasks",
        "central_locate_device",
        "central_nslookup",
        "central_ping_sweep",
        "central_probe_http",
        "central_probe_https",
        "central_probe_tcp",
        "central_reboot_device",
        "central_reboot_swarm",
        "central_speedtest",
        "central_test_aaa",
    ],
}


def register_tools(mcp: FastMCP, config: ServerConfig) -> int:
    """Load all Central tool modules and register them with FastMCP.

    Always imports every category so ``REGISTRIES["central"]`` is fully
    populated; runtime write-gating is handled by the Visibility transform
    (static mode) and ``is_tool_enabled`` (dynamic mode, via the meta-tools).

    Returns the count of individual underlying tools that registered.
    """
    from hpe_networking_mcp.platforms._common.meta_tools import build_meta_tools
    from hpe_networking_mcp.platforms.central import _registry

    _registry.mcp = mcp

    loaded: list[str] = []
    for category, tool_names in TOOLS.items():
        try:
            importlib.import_module(f"hpe_networking_mcp.platforms.central.tools.{category}")
            loaded.extend(tool_names)
            logger.debug("Central: loaded module {}", category)
        except Exception as e:
            logger.warning("Central: failed to load module {} -- {}", category, e)

    # Register prompts (register(mcp) pattern; prompts are a different MCP
    # primitive and aren't part of the dynamic-mode meta-tool surface).
    try:
        from hpe_networking_mcp.platforms.central.tools import prompts

        prompts.register(mcp)
        logger.debug("Central: loaded prompts")
    except Exception as e:
        logger.warning("Central: failed to load prompts -- {}", e)

    # Meta-tools are always registered (issue #302). In code mode they're
    # reachable via ``await call_tool("central_list_tools", ...)`` from inside
    # ``execute()`` even though they're hidden from the top-level catalog.
    # The payload-schema provider lets central_get_tool_schema surface the
    # distilled config-model field set for opaque ``payload`` dicts (#384).
    from hpe_networking_mcp.platforms.central.config_schemas import lookup_payload_schema

    build_meta_tools("central", mcp, payload_schema_provider=lookup_payload_schema)
    logger.info(
        "Central: {} underlying tools + 3 meta-tools registered ({} mode)",
        len(loaded),
        config.tool_mode,
    )

    return len(loaded)
