"""Aruba Central platform module."""

import importlib

from fastmcp import FastMCP
from loguru import logger

from hpe_networking_mcp.config import ServerConfig

# Tool categories mapped to module names and their tool names
TOOLS = {
    "sites": ["central_get_sites", "central_get_site_health", "central_get_site_name_id_mapping"],
    "devices": ["central_get_devices", "central_find_device"],
    "clients": ["central_get_clients", "central_find_client"],
    "alerts": [
        "central_get_alerts",
        "central_get_alert_classification",
        "central_get_alert_action_status",
        "central_clear_alerts",
        "central_defer_alerts",
        "central_reactivate_alerts",
        "central_set_alert_priority",
    ],
    "alert_configs": [
        "central_get_alert_configs",
        "central_create_alert_config",
        "central_update_alert_config",
        "central_reset_alert_config",
    ],
    "events": ["central_get_events", "central_get_events_count"],
    "monitoring": [
        "central_get_aps",
        "central_get_ap_wlans",
        "central_get_ap_details",
        "central_get_switch_details",
        "central_get_gateway_details",
    ],
    "wlans": ["central_get_wlans", "central_get_wlan_stats"],
    "audit_logs": ["central_get_audit_logs", "central_get_audit_log_detail"],
    "stats": [
        "central_get_ap_stats",
        "central_get_ap_utilization",
        "central_get_gateway_stats",
        "central_get_gateway_utilization",
        "central_get_gateway_wan_availability",
        "central_get_tunnel_health",
    ],
    "switch_poe": ["central_get_switch_hardware_trends", "central_get_switch_poe"],
    "applications": ["central_get_applications"],
    "troubleshooting": [
        "central_ping",
        "central_traceroute",
        "central_cable_test",
        "central_show_commands",
    ],
    "actions": [
        "central_disconnect_users_ssid",
        "central_disconnect_users_ap",
        "central_disconnect_client_switch",
        "central_disconnect_client_gateway",
        "central_disconnect_clients_gateway",
        "central_port_bounce_switch",
        "central_poe_bounce_switch",
        "central_port_bounce_gateway",
        "central_poe_bounce_gateway",
    ],
    "scope": [
        "central_get_scope_tree",
        "central_get_scope_resources",
        "central_get_committed_config",
        "central_get_effective_config",
        "central_get_devices_in_scope",
        "central_get_scope_diagram",
    ],
    "aliases": ["central_get_aliases"],
    "server_groups": ["central_get_server_groups"],
    "named_vlans": ["central_get_named_vlans"],
    "wlan_profiles": [
        "central_get_wlan_profiles",
        "central_manage_wlan_profile",
    ],
    "roles": [
        "central_get_roles",
        "central_get_role_with_policy",
        "central_manage_role",
    ],
    "security_policy": [
        "central_get_net_groups",
        "central_manage_net_group",
        "central_get_net_services",
        "central_manage_net_service",
        "central_get_object_groups",
        "central_manage_object_group",
        "central_get_role_acls",
        "central_manage_role_acl",
        "central_get_policies",
        "central_manage_policy",
    ],
    "security_policy_ext": [
        "central_get_policy_groups",
        "central_manage_policy_group",
        "central_get_policy_group_entry",
        "central_manage_policy_group_entry",
        "central_get_role_gpids",
        "central_manage_role_gpid",
    ],
    "config_assignments": [
        "central_get_config_assignments",
        "central_manage_config_assignment",
    ],
    "configuration": [
        "central_manage_site",
        "central_manage_site_collection",
        "central_manage_device_group",
    ],
    "config_health": [
        "central_get_device_config_issues",
        "central_get_devices_config_health",
        "central_resync_device_config",
    ],
    "gateway_cluster_intent": [
        "central_get_gateway_cluster_intent_profiles",
        "central_manage_gateway_cluster_intent_profile",
    ],
    "gateway_clusters": [
        "central_get_gateway_clusters",
        "central_manage_gateway_cluster",
    ],
    "firmware": ["central_recommend_firmware"],
    "translation_preview": ["central_translation_preview"],
    "wids": ["central_get_wids_monitored_aps"],
    "application_experience": [
        "central_get_app_bandwidth_contract",
        "central_manage_app_bandwidth_contract",
        "central_get_app_recog_control",
        "central_manage_app_recog_control",
        "central_get_dap",
        "central_manage_dap",
        "central_get_dap_application",
        "central_manage_dap_application",
        "central_get_dap_sla",
        "central_manage_dap_sla",
    ],
    "central_nac": [
        "central_get_cda_airpass_approval",
        "central_get_cda_auth_profile",
        "central_manage_cda_auth_profile",
        "central_get_cda_authz_policy",
        "central_manage_cda_authz_policy",
        "central_get_cda_identity_store",
        "central_manage_cda_identity_store",
        "central_get_cda_message_provider",
        "central_manage_cda_message_provider",
        "central_get_cda_portal_custom_message",
        "central_manage_cda_portal_custom_message",
        "central_get_cda_portal_default_custom_message",
        "central_manage_cda_portal_default_custom_message",
        "central_get_cda_portal_overrides_profile",
        "central_manage_cda_portal_overrides_profile",
        "central_get_cda_portal_profile",
        "central_manage_cda_portal_profile",
        "central_get_cda_portal_skin_profile",
        "central_manage_cda_portal_skin_profile",
        "central_get_cda_static_tag",
        "central_manage_cda_static_tag",
    ],
    "config_management": [
        "central_get_config_checkpoint",
        "central_manage_config_checkpoint",
        "central_manage_persona_assignment",
        "central_get_persona_mapping",
    ],
    "extensions": [
        "central_get_extension_splunk",
        "central_manage_extension_splunk",
        "central_get_extension_vsphere",
        "central_manage_extension_vsphere",
        "central_get_psm",
        "central_manage_psm",
    ],
    "firmware_policy": [
        "central_get_firmware_compliance",
        "central_manage_firmware_compliance",
    ],
    "high_availability": [
        "central_get_switch_stack",
        "central_manage_switch_stack",
        "central_get_vsf_template",
        "central_manage_vsf_template",
        "central_get_vsx",
        "central_manage_vsx",
    ],
    "interfaces": [
        "central_get_ap_port_profile",
        "central_manage_ap_port_profile",
        "central_get_ap_uplink",
        "central_manage_ap_uplink",
        "central_get_cdp",
        "central_manage_cdp",
        "central_get_device_profile",
        "central_manage_device_profile",
        "central_get_dhcp_client",
        "central_manage_dhcp_client",
        "central_get_fault_monitor",
        "central_manage_fault_monitor",
        "central_get_gw_port_profile",
        "central_manage_gw_port_profile",
        "central_get_interface_ethernet",
        "central_manage_interface_ethernet",
        "central_get_interface_loopback",
        "central_manage_interface_loopback",
        "central_get_interface_management",
        "central_manage_interface_management",
        "central_get_interface_portchannel",
        "central_manage_interface_portchannel",
        "central_get_interface_profile",
        "central_manage_interface_profile",
        "central_get_interface_subinterface",
        "central_manage_interface_subinterface",
        "central_get_interface_vlan",
        "central_manage_interface_vlan",
        "central_get_lacp",
        "central_manage_lacp",
        "central_get_lldp",
        "central_manage_lldp",
        "central_get_mirror",
        "central_manage_mirror",
        "central_get_mirror_endpoint",
        "central_manage_mirror_endpoint",
        "central_get_sflow",
        "central_manage_sflow",
        "central_get_static_mac",
        "central_manage_static_mac",
        "central_get_sw_port_profile",
        "central_manage_sw_port_profile",
        "central_get_ufd",
        "central_manage_ufd",
    ],
    "iot": [
        "central_get_usb",
        "central_manage_usb",
    ],
    "named_object": [
        "central_get_named_condition",
        "central_manage_named_condition",
    ],
    "network_services": [
        "central_get_dhcp_pool",
        "central_manage_dhcp_pool",
        "central_get_dhcp_relay",
        "central_manage_dhcp_relay",
        "central_get_dhcp_server",
        "central_manage_dhcp_server",
        "central_get_dhcp_snooping",
        "central_manage_dhcp_snooping",
        "central_get_dhcp_snooping_interface",
        "central_manage_dhcp_snooping_interface",
        "central_get_dynamic_arp_inspection_interface",
        "central_manage_dynamic_arp_inspection_interface",
        "central_get_external_storage",
        "central_manage_external_storage",
        "central_get_ip_binding",
        "central_manage_ip_binding",
        "central_get_ip_lockdown",
        "central_manage_ip_lockdown",
        "central_get_ip_lockdown_interface",
        "central_manage_ip_lockdown_interface",
        "central_get_ipsla",
        "central_manage_ipsla",
        "central_get_mgmd",
        "central_manage_mgmd",
        "central_get_multicast_dns",
        "central_manage_multicast_dns",
        "central_get_nae_lite",
        "central_manage_nae_lite",
        "central_get_nd_snooping",
        "central_manage_nd_snooping",
        "central_get_nd_snooping_interface",
        "central_manage_nd_snooping_interface",
        "central_get_ptp",
        "central_manage_ptp",
        "central_get_qos_global",
        "central_manage_qos_global",
        "central_get_qos_queue",
        "central_manage_qos_queue",
        "central_get_qos_schedule",
        "central_manage_qos_schedule",
        "central_get_qos_threshold_profile",
        "central_manage_qos_threshold_profile",
        "central_get_udp_broadcast_forwarder",
        "central_manage_udp_broadcast_forwarder",
    ],
    "routing_overlays": [
        "central_get_advanced_intelligent_forwarding",
        "central_manage_advanced_intelligent_forwarding",
        "central_get_aspath_list",
        "central_manage_aspath_list",
        "central_get_bfd",
        "central_manage_bfd",
        "central_get_bgp",
        "central_manage_bgp",
        "central_get_community_list",
        "central_manage_community_list",
        "central_get_evpn",
        "central_manage_evpn",
        "central_get_ip_routing",
        "central_manage_ip_routing",
        "central_get_l3_route",
        "central_manage_l3_route",
        "central_get_mpls",
        "central_manage_mpls",
        "central_get_msdp",
        "central_manage_msdp",
        "central_get_multicast",
        "central_manage_multicast",
        "central_get_multicast_static_route",
        "central_manage_multicast_static_route",
        "central_get_nexthop_group",
        "central_manage_nexthop_group",
        "central_get_ospfv2",
        "central_manage_ospfv2",
        "central_get_ospfv3",
        "central_manage_ospfv3",
        "central_get_pim",
        "central_manage_pim",
        "central_get_prefix_list",
        "central_manage_prefix_list",
        "central_get_rip",
        "central_manage_rip",
        "central_get_routemap",
        "central_manage_routemap",
        "central_get_static_route",
        "central_manage_static_route",
        "central_get_track_object",
        "central_manage_track_object",
        "central_get_vrf",
        "central_manage_vrf",
    ],
    "security": [
        "central_get__802dot11k",
        "central_manage__802dot11k",
        "central_get__802dot11k_bcn_rpt_req",
        "central_manage__802dot11k_bcn_rpt_req",
        "central_get__802dot11k_rrm_ie",
        "central_manage__802dot11k_rrm_ie",
        "central_get_aaa_captive_portal",
        "central_manage_aaa_captive_portal",
        "central_get_aaa_dot1xauth",
        "central_manage_aaa_dot1xauth",
        "central_get_aaa_dot1xsupp",
        "central_manage_aaa_dot1xsupp",
        "central_get_aaa_macauth",
        "central_manage_aaa_macauth",
        "central_get_aaa_profile",
        "central_manage_aaa_profile",
        "central_get_aaa_stateful_dot1x",
        "central_manage_aaa_stateful_dot1x",
        "central_get_ap_certificate_usage",
        "central_manage_ap_certificate_usage",
        "central_get_auth_server",
        "central_manage_auth_server",
        "central_get_auth_server_global",
        "central_manage_auth_server_global",
        "central_get_auth_survivability",
        "central_manage_auth_survivability",
        "central_get_certificate",
        "central_manage_certificate",
        "central_get_certificate_rcp",
        "central_manage_certificate_rcp",
        "central_get_certificate_store",
        "central_manage_certificate_store",
        "central_get_copp",
        "central_manage_copp",
        "central_get_device_certificate",
        "central_manage_device_certificate",
        "central_get_est",
        "central_manage_est",
        "central_get_firewall",
        "central_manage_firewall",
        "central_get_gw_certificate_usage",
        "central_manage_gw_certificate_usage",
        "central_get_internal_user",
        "central_manage_internal_user",
        "central_get_keychain",
        "central_manage_keychain",
        "central_get_mac_lockout",
        "central_manage_mac_lockout",
        "central_get_macsec",
        "central_manage_macsec",
        "central_get_mka",
        "central_manage_mka",
        "central_get_passpoint_identity",
        "central_manage_passpoint_identity",
        "central_get_port_security",
        "central_manage_port_security",
        "central_get_radius_modifiers",
        "central_manage_radius_modifiers",
        "central_get_ubt",
        "central_manage_ubt",
    ],
    "services": [
        "central_get_airgroup_policy",
        "central_manage_airgroup_policy",
        "central_get_airgroup_servers",
        "central_manage_airgroup_servers",
        "central_get_airgroup_service_definition",
        "central_manage_airgroup_service_definition",
        "central_get_airgroup_system",
        "central_manage_airgroup_system",
        "central_get_location",
        "central_manage_location",
    ],
    "system": [
        "central_get_ap_system",
        "central_manage_ap_system",
        "central_get_container",
        "central_manage_container",
        "central_get_container_network",
        "central_manage_container_network",
        "central_get_countermon",
        "central_manage_countermon",
        "central_get_custom_get_api",
        "central_get_db_observer",
        "central_manage_db_observer",
        "central_get_ddns",
        "central_manage_ddns",
        "central_get_dns",
        "central_manage_dns",
        "central_get_dump_server",
        "central_manage_dump_server",
        "central_get_feature_pack",
        "central_manage_feature_pack",
        "central_get_gw_system",
        "central_manage_gw_system",
        "central_get_hardware_module_profile",
        "central_manage_hardware_module_profile",
        "central_get_http_proxy",
        "central_manage_http_proxy",
        "central_get_ip_source_interface",
        "central_manage_ip_source_interface",
        "central_get_ipm",
        "central_manage_ipm",
        "central_get_job_scheduler",
        "central_manage_job_scheduler",
        "central_get_local_management",
        "central_manage_local_management",
        "central_get_logging",
        "central_manage_logging",
        "central_get_management_user",
        "central_manage_management_user",
        "central_get_management_user_group",
        "central_manage_management_user_group",
        "central_get_nae_agent",
        "central_manage_nae_agent",
        "central_get_nae_script",
        "central_manage_nae_script",
        "central_get_ntp",
        "central_manage_ntp",
        "central_get_packet_capture",
        "central_manage_packet_capture",
        "central_get_remote_management",
        "central_manage_remote_management",
        "central_get_rmon_alarm",
        "central_manage_rmon_alarm",
        "central_get_snmp",
        "central_manage_snmp",
        "central_get_snmp_trap",
        "central_manage_snmp_trap",
        "central_get_speed_test",
        "central_manage_speed_test",
        "central_get_switch_chassis",
        "central_manage_switch_chassis",
        "central_get_switch_profiles",
        "central_manage_switch_profiles",
        "central_get_switch_system",
        "central_manage_switch_system",
        "central_get_sysmon",
        "central_manage_sysmon",
        "central_get_system_info",
        "central_manage_system_info",
        "central_get_telemetry",
        "central_manage_telemetry",
        "central_get_timerange",
        "central_manage_timerange",
    ],
    "telemetry": [
        "central_get_client_insight",
        "central_manage_client_insight",
        "central_get_client_iptracker",
        "central_manage_client_iptracker",
        "central_get_client_iptracker_interface",
        "central_manage_client_iptracker_interface",
        "central_get_devicefingerprinting",
        "central_manage_devicefingerprinting",
        "central_get_devicefingerprinting_interface",
        "central_manage_devicefingerprinting_interface",
        "central_get_devicefingerprinting_profile",
        "central_manage_devicefingerprinting_profile",
        "central_get_flow_tracking",
        "central_manage_flow_tracking",
        "central_get_ipfix_flow_exporter",
        "central_manage_ipfix_flow_exporter",
        "central_get_traffic_insight",
        "central_manage_traffic_insight",
    ],
    "tunnels": [
        "central_get_interface_tunnel",
        "central_manage_interface_tunnel",
        "central_get_interface_tunnel_group",
        "central_manage_interface_tunnel_group",
    ],
    "uncategorized": [
        "central_get_db_data_migration",
        "central_manage_db_data_migration",
        "central_get_dsm",
        "central_manage_dsm",
        "central_get_feature_property",
        "central_manage_feature_property",
        "central_get_firmware_management",
        "central_manage_firmware_management",
        "central_get_interface_vxlan",
        "central_manage_interface_vxlan",
        "central_get_overlay_wlan",
        "central_manage_overlay_wlan",
        "central_get_vsx_pair",
        "central_manage_vsx_pair",
    ],
    "vlans_networks": [
        "central_get_erps",
        "central_manage_erps",
        "central_get_gw_stp",
        "central_manage_gw_stp",
        "central_get_loop_protect",
        "central_manage_loop_protect",
        "central_get_mvrp",
        "central_manage_mvrp",
        "central_get_smartlink",
        "central_manage_smartlink",
        "central_get_static_neighbor",
        "central_manage_static_neighbor",
        "central_get_stp",
        "central_manage_stp",
        "central_get_vlan",
        "central_manage_vlan",
        "central_manage_vlan_range",
        "central_get_vrrp",
        "central_manage_vrrp",
        "central_get_vrrp_interface",
        "central_manage_vrrp_interface",
    ],
    "wireless": [
        "central_get_alg",
        "central_manage_alg",
        "central_get_ids",
        "central_manage_ids",
        "central_get_mesh",
        "central_manage_mesh",
        "central_get_mpsk_local",
        "central_manage_mpsk_local",
        "central_get_passpoint",
        "central_manage_passpoint",
        "central_get_radio",
        "central_manage_radio",
    ],
    "mrt_msp": [
        "central_list_msp_tenants",
    ],
    "mrt_insights": [
        "central_get_insights",
    ],
    "mrt_reporting": [
        "central_get_reports",
        "central_get_report_runs",
        "central_update_report",
    ],
    "mrt_webhooks": [
        "central_get_webhooks",
        "central_get_webhook",
        "central_manage_webhook",
        "central_rotate_webhook_hmac_key",
    ],
    "mrt_services": [
        "central_get_fco_resp_info",
        "central_get_fco_resp_info_all",
        "central_get_asset_tags",
        "central_get_asset_tag",
        "central_manage_asset_tag_metadata",
        "central_start_ap_ranging_scan",
        "central_get_ap_ranging_scans",
        "central_get_ap_ranging_scan",
        "central_delete_ap_ranging_scan",
        "central_get_site_device_locations",
        "central_get_site_device_location",
        "central_get_device_location",
        "central_manage_device_location",
        "central_get_wifi_clients_locations",
        "central_get_location_analytics_trends",
        "central_get_location_analytics_site_insights",
    ],
    "mrt_sitemaps": [
        "central_get_sitemap_summary",
        "central_get_catalogue_aps",
        "central_get_sitemap_devices",
        "central_manage_sitemap_devices",
        "central_get_floor",
        "central_manage_floor",
        "central_set_floor_scale",
        "central_get_floor_image",
        "central_set_floor_image",
        "central_get_buildings",
        "central_manage_building",
        "central_import_sitemap",
        "central_get_sitemap_import_status",
        "central_get_wall_types",
        "central_manage_wall_types",
        "central_get_floor_walls",
        "central_manage_floor_walls",
        "central_get_floor_zones",
        "central_manage_floor_zones",
    ],
    "mrt_health": [
        "central_get_site_health_detail",
        "central_get_sites_client_health",
        "central_get_tenant_device_health",
        "central_get_tenant_client_health",
    ],
    "mrt_clients": [
        "central_get_clients_trend",
        "central_get_clients_topn_usage",
        "central_get_client_mobility_trail",
        "central_get_client_detail",
        "central_get_client_onboarding_score",
        "central_get_client_onboarding_stage_export",
        "central_get_client_onboarding_stage_reasons",
        "central_get_client_onboarding_stage_count",
        "central_get_firewall_sessions",
    ],
    "mrt_topology": [
        "central_get_topology",
        "central_get_neighbours",
        "central_get_unmanaged_device",
        "central_get_isolated_devices",
        "central_get_device_inventory",
        "central_update_device",
        "central_delete_device",
    ],
    "mrt_switch": [
        "central_get_switches",
        "central_get_switch_lag",
        "central_get_switch_vlans",
        "central_get_switch_hardware_categories",
        "central_get_switch_interface_trends",
        "central_get_switches_topn_interface_trends",
        "central_get_switch_vsx",
        "central_get_switch_stack_members",
    ],
    "mrt_ap": [
        "central_get_ap_trend",
        "central_get_ap_radios",
        "central_get_ap_radio_trend",
        "central_get_ap_ports",
        "central_get_ap_port_trend",
        "central_get_ap_tunnels",
        "central_get_ap_tunnel",
        "central_get_ap_tunnel_trend",
        "central_get_ap_wlans_monitoring",
        "central_get_ap_wlan_throughput",
        "central_get_top_aps_by_usage",
        "central_get_radios",
        "central_get_bssids",
        "central_get_wlans_monitoring",
        "central_get_wlan_monitoring_detail",
        "central_get_swarms",
        "central_get_swarm",
        "central_get_applications_v1",
    ],
    "mrt_gateway": [
        "central_get_gateways",
        "central_get_gateway_trend",
        "central_get_gateway_ports",
        "central_get_gateway_port",
        "central_get_gateway_port_trend",
        "central_get_gateway_tunnels",
        "central_get_gateway_tunnel",
        "central_get_gateway_tunnel_trend",
        "central_get_gateway_tunnels_health_summary",
        "central_get_gateway_vlans_runtime",
        "central_get_gateway_vlan_runtime",
        "central_get_gateway_uplinks",
        "central_get_gateway_uplink",
        "central_get_gateway_uplink_trend",
        "central_get_gateway_uplink_probes",
        "central_get_gateway_uplink_probe_performance",
        "central_get_gateway_uplink_vpn_availability",
        "central_get_gateway_dhcp",
        "central_get_cluster_members",
        "central_get_cluster_summary",
        "central_get_cluster_capacity_trends",
    ],
    "mrt_troubleshooting": [
        "central_get_troubleshooting_task_status",
        "central_list_troubleshooting_tasks",
        "central_list_supported_show_commands",
        "central_get_event_extra_attributes",
        "central_probe_http",
        "central_probe_https",
        "central_probe_tcp",
        "central_iperf_test",
        "central_speedtest",
        "central_nslookup",
        "central_test_aaa",
        "central_get_arp_table",
        "central_ping_sweep",
        "central_reboot_device",
        "central_reboot_swarm",
        "central_locate_device",
        "central_halt_gateway",
        "central_disconnect_user_by_network",
        "central_disconnect_user_by_mac_on_ap",
        "central_disconnect_user_all_on_ap",
        "central_disconnect_client_all_on_gateway",
        "central_disconnect_client_by_mac_on_gateway",
    ],
}


def register_tools(mcp: FastMCP, config: ServerConfig) -> int:
    """Load all Central tool modules and register them with FastMCP.

    Always imports every category so ``REGISTRIES["central"]`` is fully
    populated; runtime write-gating is handled by the Visibility transform
    (static mode) and ``is_tool_enabled`` (dynamic mode, via the meta-tools).

    Returns the count of individual underlying tools that registered.
    """
    from hpe_networking_mcp.platforms._common.meta_tools import build_meta_tools
    from hpe_networking_mcp.platforms.central import _registry

    _registry.mcp = mcp

    loaded: list[str] = []
    for category, tool_names in TOOLS.items():
        try:
            importlib.import_module(f"hpe_networking_mcp.platforms.central.tools.{category}")
            loaded.extend(tool_names)
            logger.debug("Central: loaded module {}", category)
        except Exception as e:
            logger.warning("Central: failed to load module {} -- {}", category, e)

    # Register prompts (register(mcp) pattern; prompts are a different MCP
    # primitive and aren't part of the dynamic-mode meta-tool surface).
    try:
        from hpe_networking_mcp.platforms.central.tools import prompts

        prompts.register(mcp)
        logger.debug("Central: loaded prompts")
    except Exception as e:
        logger.warning("Central: failed to load prompts -- {}", e)

    # Meta-tools are always registered (issue #302). In code mode they're
    # reachable via ``await call_tool("central_list_tools", ...)`` from inside
    # ``execute()`` even though they're hidden from the top-level catalog.
    build_meta_tools("central", mcp)
    logger.info(
        "Central: {} underlying tools + 3 meta-tools registered ({} mode)",
        len(loaded),
        config.tool_mode,
    )

    return len(loaded)
