"""HPE GreenLake platform module.

Spec-driven: the tool surface is generated from the vendored GreenLake OpenAPI
specs under ``vendor/greenlake/`` (manifest: ``vendor/greenlake/sources.json``).
Each generated tool follows the ``greenlake_<method>_<path-slug>`` naming
convention and calls into ``client.greenlake_request`` for transport (which
auto-polls GreenLake's 202 + async-operation writes to a terminal result).

These tool modules are committed and are the source of truth at runtime. They
are regenerated by a **maintainer-local** generator that is intentionally NOT
committed (project policy: generators stay local — see ``.gitignore``).
Regeneration is a deliberate release-time step.

The hand-written ``bulk_add`` orchestration tool (+ its ``_bulk_*`` helpers) is
kept alongside the generated modules — it is not a thin spec wrapper but a
batching/rate-limiting/resume/subscription-assignment workflow.
"""

from __future__ import annotations

import importlib
import pkgutil

from fastmcp import FastMCP
from loguru import logger

from hpe_networking_mcp.config import ServerConfig


def register_tools(mcp_instance: FastMCP, config: ServerConfig) -> int:
    """Load every GreenLake tool module (generated + hand-written) and register them.

    Walks ``platforms.greenlake.tools`` and imports each non-underscore submodule;
    the ``@tool(...)`` decorators record each tool with FastMCP via the shared
    ``_registry.tool`` shim. ``_``-prefixed modules (``_bulk_*``) are skipped.

    Returns the count of tools that registered (not incl. the 3 meta-tools) —
    the module count is much smaller (one module holds many tools), so it must
    not be conflated with the tool count in logs.
    """
    from hpe_networking_mcp.platforms._common.meta_tools import build_meta_tools
    from hpe_networking_mcp.platforms._common.tool_registry import REGISTRIES
    from hpe_networking_mcp.platforms.greenlake import _registry

    # Wire the FastMCP holder BEFORE importing the tools package so the ``@tool``
    # decorators register with FastMCP (not just record specs).
    _registry.mcp = mcp_instance

    from hpe_networking_mcp.platforms.greenlake import tools as tools_pkg

    loaded: list[str] = []
    for _finder, modname, _ispkg in pkgutil.iter_modules(tools_pkg.__path__):
        if modname.startswith("_"):
            continue
        try:
            importlib.import_module(f"{tools_pkg.__name__}.{modname}")
            loaded.append(modname)
        except Exception as exc:
            logger.warning("GreenLake: failed to load tool module {} -- {}", modname, exc)

    # Meta-tools are always registered (issue #302). In code mode they're
    # reachable via ``await call_tool("greenlake_list_tools", ...)`` from inside
    # ``execute()`` even though they're hidden from the top-level catalog.
    build_meta_tools("greenlake", mcp_instance)
    tool_count = len(REGISTRIES["greenlake"])
    logger.info(
        "GreenLake: registered {} tools across {} tool module(s) + 3 meta-tools ({} mode)",
        tool_count,
        len(loaded),
        config.tool_mode,
    )

    return tool_count
