"""Auto-generated Mist tools — see ``_generator.py``."""

# ruff: noqa: F401

from . import (
    admins,  # noqa: F401
    admins_login,  # noqa: F401
    admins_login_oauth2,  # noqa: F401
    admins_logout,  # noqa: F401
    admins_lookup,  # noqa: F401
    admins_recover_password,  # noqa: F401
    constants_definitions,  # noqa: F401
    constants_events,  # noqa: F401
    constants_models,  # noqa: F401
    installer,  # noqa: F401
    msps,  # noqa: F401
    msps_admins,  # noqa: F401
    msps_inventory,  # noqa: F401
    msps_licenses,  # noqa: F401
    msps_logo,  # noqa: F401
    msps_logs,  # noqa: F401
    msps_marvis,  # noqa: F401
    msps_org_groups,  # noqa: F401
    msps_orgs,  # noqa: F401
    msps_sles,  # noqa: F401
    msps_sso,  # noqa: F401
    msps_sso_roles,  # noqa: F401
    msps_tickets,  # noqa: F401
    orgs,  # noqa: F401
    orgs_admins,  # noqa: F401
    orgs_advanced_anti_malware_profiles,  # noqa: F401
    orgs_alarm_templates,  # noqa: F401
    orgs_alarms,  # noqa: F401
    orgs_antivirus_profiles,  # noqa: F401
    orgs_ap_templates,  # noqa: F401
    orgs_api_tokens,  # noqa: F401
    orgs_asset_filters,  # noqa: F401
    orgs_assets,  # noqa: F401
    orgs_cert,  # noqa: F401
    orgs_clients_marvis,  # noqa: F401
    orgs_clients_nac,  # noqa: F401
    orgs_clients_sdk,  # noqa: F401
    orgs_clients_wan,  # noqa: F401
    orgs_clients_wired,  # noqa: F401
    orgs_clients_wireless,  # noqa: F401
    orgs_crl,  # noqa: F401
    orgs_device_profiles,  # noqa: F401
    orgs_devices,  # noqa: F401
    orgs_devices_aos,  # noqa: F401
    orgs_devices_others,  # noqa: F401
    orgs_devices_ssr,  # noqa: F401
    orgs_events,  # noqa: F401
    orgs_evpn_topologies,  # noqa: F401
    orgs_gateway_templates,  # noqa: F401
    orgs_guests,  # noqa: F401
    orgs_idp_profiles,  # noqa: F401
    orgs_integration_cradlepoint,  # noqa: F401
    orgs_integration_jse,  # noqa: F401
    orgs_integration_juniper,  # noqa: F401
    orgs_integration_skyatp,  # noqa: F401
    orgs_integration_zscaler,  # noqa: F401
    orgs_inventory,  # noqa: F401
    orgs_jsi,  # noqa: F401
    orgs_licenses,  # noqa: F401
    orgs_linked_applications,  # noqa: F401
    orgs_logs,  # noqa: F401
    orgs_maps,  # noqa: F401
    orgs_marvis,  # noqa: F401
    orgs_marvis_invites,  # noqa: F401
    orgs_mxclusters,  # noqa: F401
    orgs_mxedges,  # noqa: F401
    orgs_mxtunnels,  # noqa: F401
    orgs_nac_crl,  # noqa: F401
    orgs_nac_idp,  # noqa: F401
    orgs_nac_portals,  # noqa: F401
    orgs_nac_rules,  # noqa: F401
    orgs_nac_tags,  # noqa: F401
    orgs_network_templates,  # noqa: F401
    orgs_networks,  # noqa: F401
    orgs_premium_analytics,  # noqa: F401
    orgs_psk_portals,  # noqa: F401
    orgs_psks,  # noqa: F401
    orgs_reports,  # noqa: F401
    orgs_rf_templates,  # noqa: F401
    orgs_scep,  # noqa: F401
    orgs_sdk_invites,  # noqa: F401
    orgs_sdk_templates,  # noqa: F401
    orgs_secintel_profiles,  # noqa: F401
    orgs_security_policies,  # noqa: F401
    orgs_service_policies,  # noqa: F401
    orgs_services,  # noqa: F401
    orgs_setting,  # noqa: F401
    orgs_site_templates,  # noqa: F401
    orgs_sitegroups,  # noqa: F401
    orgs_sites,  # noqa: F401
    orgs_sles,  # noqa: F401
    orgs_sso,  # noqa: F401
    orgs_sso_roles,  # noqa: F401
    orgs_stats,  # noqa: F401
    orgs_stats_assets,  # noqa: F401
    orgs_stats_bgp_peers,  # noqa: F401
    orgs_stats_devices,  # noqa: F401
    orgs_stats_mxedges,  # noqa: F401
    orgs_stats_ospf,  # noqa: F401
    orgs_stats_other_devices,  # noqa: F401
    orgs_stats_ports,  # noqa: F401
    orgs_stats_sites,  # noqa: F401
    orgs_stats_tunnels,  # noqa: F401
    orgs_stats_vpn_peers,  # noqa: F401
    orgs_tickets,  # noqa: F401
    orgs_ui_settings,  # noqa: F401
    orgs_user_macs,  # noqa: F401
    orgs_vars,  # noqa: F401
    orgs_vpns,  # noqa: F401
    orgs_webhooks,  # noqa: F401
    orgs_wlan_templates,  # noqa: F401
    orgs_wlans,  # noqa: F401
    orgs_wxrules,  # noqa: F401
    orgs_wxtags,  # noqa: F401
    orgs_wxtunnels,  # noqa: F401
    self_account,  # noqa: F401
    self_alarms,  # noqa: F401
    self_api_token,  # noqa: F401
    self_audit_logs,  # noqa: F401
    self_mfa,  # noqa: F401
    self_oauth2,  # noqa: F401
    sites,  # noqa: F401
    sites_advanced_anti_malware_profiles,  # noqa: F401
    sites_alarms,  # noqa: F401
    sites_anomaly,  # noqa: F401
    sites_antivirus_profiles,  # noqa: F401
    sites_ap_templates,  # noqa: F401
    sites_applications,  # noqa: F401
    sites_asset_filters,  # noqa: F401
    sites_assets,  # noqa: F401
    sites_auto_map_assignment,  # noqa: F401
    sites_beacons,  # noqa: F401
    sites_clients_nac,  # noqa: F401
    sites_clients_wan,  # noqa: F401
    sites_clients_wired,  # noqa: F401
    sites_clients_wireless,  # noqa: F401
    sites_device_profiles,  # noqa: F401
    sites_devices,  # noqa: F401
    sites_devices_others,  # noqa: F401
    sites_devices_wan_cluster,  # noqa: F401
    sites_devices_wired,  # noqa: F401
    sites_devices_wired_virtual_chassis,  # noqa: F401
    sites_devices_wireless,  # noqa: F401
    sites_events,  # noqa: F401
    sites_evpn_topologies,  # noqa: F401
    sites_gateway_templates,  # noqa: F401
    sites_guests,  # noqa: F401
    sites_idp_profiles,  # noqa: F401
    sites_insights,  # noqa: F401
    sites_jse,  # noqa: F401
    sites_licenses,  # noqa: F401
    sites_location,  # noqa: F401
    sites_map_stacks,  # noqa: F401
    sites_maps,  # noqa: F401
    sites_maps_auto_placement,  # noqa: F401
    sites_maps_auto_zone,  # noqa: F401
    sites_mxedges,  # noqa: F401
    sites_nac_fingerprints,  # noqa: F401
    sites_network_templates,  # noqa: F401
    sites_networks,  # noqa: F401
    sites_psks,  # noqa: F401
    sites_rf_templates,  # noqa: F401
    sites_rfdiags,  # noqa: F401
    sites_rogues,  # noqa: F401
    sites_rrm,  # noqa: F401
    sites_rssi_zones,  # noqa: F401
    sites_secintel_profiles,  # noqa: F401
    sites_service_policies,  # noqa: F401
    sites_services,  # noqa: F401
    sites_setting,  # noqa: F401
    sites_site_templates,  # noqa: F401
    sites_skyatp,  # noqa: F401
    sites_sles,  # noqa: F401
    sites_spectrum_analysis,  # noqa: F401
    sites_stats,  # noqa: F401
    sites_stats_apps,  # noqa: F401
    sites_stats_assets,  # noqa: F401
    sites_stats_beacons,  # noqa: F401
    sites_stats_bgp_peers,  # noqa: F401
    sites_stats_calls,  # noqa: F401
    sites_stats_clients_sdk,  # noqa: F401
    sites_stats_clients_wireless,  # noqa: F401
    sites_stats_devices,  # noqa: F401
    sites_stats_discovered_switches,  # noqa: F401
    sites_stats_iot_endpoints,  # noqa: F401
    sites_stats_mxedges,  # noqa: F401
    sites_stats_ospf,  # noqa: F401
    sites_stats_ports,  # noqa: F401
    sites_stats_wxrules,  # noqa: F401
    sites_stats_zones,  # noqa: F401
    sites_synthetic_tests,  # noqa: F401
    sites_ui_settings,  # noqa: F401
    sites_vbeacons,  # noqa: F401
    sites_vpns,  # noqa: F401
    sites_wan_usages,  # noqa: F401
    sites_webhooks,  # noqa: F401
    sites_wlans,  # noqa: F401
    sites_wxrules,  # noqa: F401
    sites_wxtags,  # noqa: F401
    sites_wxtunnels,  # noqa: F401
    sites_zones,  # noqa: F401
    utilities_common,  # noqa: F401
    utilities_lan,  # noqa: F401
    utilities_location,  # noqa: F401
    utilities_mxedge,  # noqa: F401
    utilities_pcaps,  # noqa: F401
    utilities_upgrade,  # noqa: F401
    utilities_wan,  # noqa: F401
    utilities_wi_fi,  # noqa: F401
)
