"""Generated Mist tools — DO NOT EDIT BY HAND.

This file was emitted by ``scripts/_mist_generator.py`` from
``vendor/mist_openapi.json``. Regenerate via:

    uv run python scripts/regenerate_mist_tools.py

Tag: ``Self MFA``
Operations in this file: 2
"""

# ruff: noqa: E501

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import Context
from mcp.types import ToolAnnotations
from pydantic import Field

from hpe_networking_mcp.platforms.mist._client import mist_request
from hpe_networking_mcp.platforms.mist._registry import tool as _mcp_tool


@_mcp_tool(
    name="mist_generate_secret_for2fa_verification",
    description="GET /api/v1/self/two_factor/token\n\ngenerateSecretFor2faVerification\n\nGenerate Secret Key for 2FA verification",
    tags={"mist"},
    annotations=ToolAnnotations(readOnlyHint=True, destructiveHint=False),
)
async def mist_generate_secret_for2fa_verification(
    ctx: Context,
    by: Annotated[Any | None, Field(description="If `by`==`qrcode`, returns the secret as a qrcode image")] = None,
) -> Any:
    return await mist_request(
        ctx,
        "GET",
        "/api/v1/self/two_factor/token",
        path_params=None,
        query_params={"by": by},
        body=None,
    )


@_mcp_tool(
    name="mist_verify_two_factor",
    description="POST /api/v1/self/two_factor/verify\n\nverifyTwoFactor\n\nVerify Two-factor (OTP)\n\nTo verify two-factor authentication by using a code generated by app (e.g. Google Authenticator, Authy). Upon successful verification, the `two_factor_passed` will be set to true if it hasn’t already been.",
    tags={"mist", "mist_write"},
    annotations=ToolAnnotations(readOnlyHint=False, destructiveHint=False),
)
async def mist_verify_two_factor(
    ctx: Context,
    body: Annotated[dict[str, Any] | None, Field(default=None, description="Request Body")] = None,
) -> Any:
    return await mist_request(
        ctx,
        "POST",
        "/api/v1/self/two_factor/verify",
        path_params=None,
        query_params=None,
        body=body,
    )
