"""Integration-style unit tests for GreenLake dynamic-mode alignment (#162).

Mirrors the other four platform registry tests. Imports every GreenLake tool
module against the stubbed mcp (installed in ``tests/conftest.py``) and
asserts the shared registry ends up populated with the expected specs.
"""

from __future__ import annotations

import importlib

import pytest

from hpe_networking_mcp.platforms._common.tool_registry import REGISTRIES, clear_registry


@pytest.fixture
def greenlake_registry_populated():
    """Import every GreenLake tool module so ``REGISTRIES['greenlake']`` is full."""
    clear_registry("greenlake")
    from hpe_networking_mcp.platforms.greenlake.tools import TOOLS

    for category in TOOLS:
        module = importlib.import_module(f"hpe_networking_mcp.platforms.greenlake.tools.{category}")
        importlib.reload(module)
    yield REGISTRIES["greenlake"]
    clear_registry("greenlake")


@pytest.mark.unit
class TestGreenLakeRegistryPopulation:
    def test_registry_contains_all_tools(self, greenlake_registry_populated):
        """Every GreenLake tool listed in TOOLS registers cleanly."""
        from hpe_networking_mcp.platforms.greenlake.tools import TOOLS

        expected = {name for names in TOOLS.values() for name in names}
        actual = set(greenlake_registry_populated.keys())
        assert actual == expected, f"Mismatch — missing: {expected - actual}, extra: {actual - expected}"

    def test_expected_surface_size(self, greenlake_registry_populated):
        """GreenLake has exactly 10 tools (2 per service × 5 services)."""
        assert len(greenlake_registry_populated) == 10

    def test_greenlake_has_no_write_gate(self, greenlake_registry_populated):
        """GreenLake is read-only today — no tool should carry a write tag."""
        for name, spec in greenlake_registry_populated.items():
            write_tags = {"greenlake_write", "greenlake_write_delete"}
            assert not (spec.tags & write_tags), f"{name} unexpectedly carries a write tag"

    def test_categories_derived_from_module_names(self, greenlake_registry_populated):
        """Category == source module short name."""
        assert greenlake_registry_populated["greenlake_get_devices"].category == "devices"
        assert greenlake_registry_populated["greenlake_get_audit_logs"].category == "audit_logs"
        assert greenlake_registry_populated["greenlake_get_subscriptions"].category == "subscriptions"
        assert greenlake_registry_populated["greenlake_get_users"].category == "users"
        assert greenlake_registry_populated["greenlake_get_workspace"].category == "workspaces"

    def test_descriptions_are_populated(self, greenlake_registry_populated):
        for name, spec in greenlake_registry_populated.items():
            assert spec.description, f"{name} has empty description"

    def test_old_endpoint_dispatch_tool_names_not_in_registry(self, greenlake_registry_populated):
        """Phase 4 removed the REST-endpoint-dispatch meta-tools from v0.9.x.

        Their names (``greenlake_list_endpoints`` etc.) should NOT appear in
        the registry. The new meta-tools (``greenlake_list_tools`` etc.) are
        generated by ``build_meta_tools`` and not registered in REGISTRIES.
        """
        for legacy in ("greenlake_list_endpoints", "greenlake_get_endpoint_schema", "greenlake_invoke_endpoint"):
            assert legacy not in greenlake_registry_populated
